Add performance testing to conformance tests
DataBiosphere/wdl-conformance-tests pull request #23
Opened 2023-12-12 20:30 UTC by stxue1

- Added some integration tests under `integration/`
- Added `performance_testing.py` to run and time tests and output results to a CSV file
- Added `create_graph.py` to read from CSV file (or run performance testing itself) and display/output graphs
- Added support for runner specific arguments in `run.py`
- Tests will run on individual processes instead of threads in order to properly time the tests
- Refactored `run.py` in order to be callable + separated out common functions into `lib.py`
- Added `merge.py` to merge CSV files
- `dir` field in `conformance.yaml` is now specified from project root directory
- Added `id` field to `conformance.yaml`
- Added `--id`, `--repeat`, `--exclude-numbers` for better specification when running tests

2023-12-14 20:03 UTC, adamnovak requested changes

2023-12-14 20:03 UTC, adamnovak commented on performance_testing.py
> +    parser = argparse.ArgumentParser()
This should probably have some top-level help text to explain what the tool is for or how to use it.

2023-12-14 20:03 UTC, adamnovak commented on performance_testing.py
This should probably be `run_performance.py` or something else that sounds more like a command and not a library.

2023-12-14 20:03 UTC, adamnovak commented on create_graph.py
> +    parser = argparse.ArgumentParser()
This script could also use some top-level help.

2024-01-11 17:52 UTC, stxue1 commented on integration/tut01/helloHaplotypeCaller.wdl
I modified some of the original files from the [WDL GATK tutorials](https://support.terra.bio/hc/en-us/articles/360037127992--1-howto-Write-your-first-WDL-script-running-GATK-HaplotypeCaller), which links to a [github repo](https://github.com/openwdl/wdl-docs) that has a BSD3 license. I probably could move them into S3, but I did modify the files so I'm not sure how pulling files in from S3 would work then.

2024-01-16 17:08 UTC, merged